### ISSUE TITLE
Invalid attempt to destructure non-iterable instance

### ISSUE THREAD

**Issue by mmmeff** [zeit/styled-jsx#151]
Sup sup,

I just switched my Next@beta39 app over from glamor to styled-jsx and I'm now receiving a module build error on any component that uses `<style jsx>{ ... }</style>` tags.

Stack trace:
```
 Module build failed: TypeError: /Users/blah/code/myappblah/pages/_document.js?entry: Invalid attempt to destructure non-iterable instance
     at /Users/blah/code/myappblah/node_modules/styled-jsx/dist/babel.js:7:585
     at PluginPass.exit (/Users/blah/code/myappblah/node_modules/styled-jsx/dist/babel.js:287:38)
     at newFn (/Users/blah/code/myappblah/node_modules/babel-core/node_modules/babel-traverse/lib/visitors.js:276:21)
     at NodePath._call (/Users/blah/code/myappblah/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:76:18)
     at NodePath.call (/Users/blah/code/myappblah/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:48:17)
     at NodePath.visit (/Users/blah/code/myappblah/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:117:8)
     at TraversalContext.visitQueue (/Users/blah/code/myappblah/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:150:16)
     at TraversalContext.visitMultiple (/Users/blah/code/myappblah/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:103:17)
     at TraversalContext.visit (/Users/blah/code/myappblah/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:190:19)
     at Function.traverse.node (/Users/blah/code/myappblah/node_modules/babel-core/node_modules/babel-traverse/lib/index.js:114:17)
```

Example module: 
```jsx
import React from 'react';
import Document, { Head, Main, NextScript } from 'next/document';
import flush from 'styled-jsx/server';


export default class MainDocument extends Document {
    static getInitialProps({ renderPage }) {
        const { html, head } = renderPage();
        const styles = flush();
        return { html, head, styles };
    }

    render() {
        return (
            <html>
                <Head>
                    <link href="//unpkg.com/antd/dist/antd.min.css" rel="stylesheet" />
                    <link rel="shortcut icon" type="image/png" href="/static/logo_square.png" />

                    { this.props.head }
                    { this.props.styles }
                </Head>

                <body>
                    <style jsx>{`
                        body {
                            background: #FAFAFA;
                            font-size: 14px;
                            min-height: 100vh;
                        }
                    `}
                    </style>

                    <div className="app-container">
                        <style jsx>{`
                            .app-container {
                                padding: 33px;
                            }
                        `}</style>

                        <Main />
                    </div>

                    <NextScript />
                </body>
            </html>
        );
    }
}
```

I'm not sure if this falls into Next's domain more than styled-jsx, but given that the stack trace originates from the babel-compiled styled-jsx module, I figured I'd start here.

**Comment by giuseppeg** [comment]
@mmmeff this is because we don't support nested styled-jsx tags see #42

**Comment by mmmeff** [comment]
Thanks @giuseppeg - I agree with the conversation in #42 that the solution here is to improve error messages to explain where I went wrong.
