### ISSUE TITLE
Invalid array length using external stylesheet import with global attribute

### ISSUE THREAD

**Issue by kozy** [zeit/styled-jsx#191]
Using master at d6785e and the current stable nextjs. Without the global attribute it works fine

```
Module build failed: RangeError: src/pages/products/show.js?entry: Invalid array length
    at PluginPass.enter (node_modules/styled-jsx/dist/babel.js:191:131)
    at newFn (node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (node_modules/babel-traverse/lib/path/context.js:76:18)

...
```

**Comment by giuseppeg** [comment]
@kozy good catch I'll put together a fix asap!
