### ISSUE TITLE
External stylesheets break with Prettier 1.5.0

### ISSUE THREAD

**Issue by leo** [zeit/styled-jsx#251]
In some cases, this:

```jsx
<style jsx>{styles}</style>
```

...becomes this:

```jsx
<style jsx>
  {styles}
</style>
```

The above throws an error. Not sure if it's a Next.js issue or not.

**Comment by rauchg** [comment]
What's the error?

**Comment by giuseppeg** [comment]
@leo what is the stack trace?

**Comment by leo** [comment]
Whoops, sorry!

```
> Using "webpack" config function defined in next.config.js.
> Failed to build on /var/folders/c0/ns546fkj6t52nvlsm2zvm6p40000gn/T/8f4b0e64-cfbf-478b-a9e7-81600f7e9c73
{ Error: ./renderer/components/feed/switcher.js
Module build failed: TypeError: /Users/leo/Projects/now-desktop-stage/renderer/components/feed/switcher.js: Invalid attempt to destructure non-iterable instance
    at /Users/leo/Projects/now-desktop-stage/node_modules/babel-runtime/helpers/slicedToArray.js:48:13
    at PluginPass.exit (/Users/leo/Projects/now-desktop-stage/node_modules/styled-jsx/dist/babel.js:250:66)
    at newFn (/Users/leo/Projects/now-desktop-stage/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/Users/leo/Projects/now-desktop-stage/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/leo/Projects/now-desktop-stage/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/leo/Projects/now-desktop-stage/node_modules/babel-traverse/lib/path/context.js:117:8)
    at TraversalContext.visitQueue (/Users/leo/Projects/now-desktop-stage/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/Users/leo/Projects/now-desktop-stage/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/Users/leo/Projects/now-desktop-stage/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/Users/leo/Projects/now-desktop-stage/node_modules/babel-traverse/lib/index.js:114:17)
 @ ./renderer/pages/feed.js?entry 105:16-54
 @ multi ./pages/feed.js?entry
    at /Users/leo/Projects/now-desktop-stage/node_modules/next/dist/server/build/index.js:182:21
    at /Users/leo/Projects/now-desktop-stage/node_modules/webpack/lib/Compiler.js:272:15
    at Compiler.emitRecords (/Users/leo/Projects/now-desktop-stage/node_modules/webpack/lib/Compiler.js:367:37)
    at /Users/leo/Projects/now-desktop-stage/node_modules/webpack/lib/Compiler.js:265:12
    at /Users/leo/Projects/now-desktop-stage/node_modules/webpack/lib/Compiler.js:360:11
    at next (/Users/leo/Projects/now-desktop-stage/node_modules/tapable/lib/Tapable.js:154:11)
    at Compiler.compiler.plugin (/Users/leo/Projects/now-desktop-stage/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/Users/leo/Projects/now-desktop-stage/node_modules/tapable/lib/Tapable.js:158:13)
    at Compiler.afterEmit (/Users/leo/Projects/now-desktop-stage/node_modules/webpack/lib/Compiler.js:357:8)
    at Compiler.<anonymous> (/Users/leo/Projects/now-desktop-stage/node_modules/webpack/lib/Compiler.js:352:14)
```

**Comment by giuseppeg** [comment]
ah yeah damn `JSXText` :)

The bug is here https://github.com/zeit/styled-jsx/blob/master/src/babel.js#L270

We should get the first non-JSXText child.

**Comment by leo** [comment]
Is there a chance that we can get this fixed an released (+ bumped in next.js)? There's something coming up and I've love to have this in there.

**Comment by giuseppeg** [comment]
I don't have time tonight but the fix could be as easy as:

```js
if (
  state.externalStyles.length > 0 &&
  path.get('children').filter(child => {
    const expression = child.get('expression')
    return expression && expression.isIdentifier()
  }).length === 1
) {
```

(haven't thought of edge cases) can you submit a PR?

**Comment by akupila** [comment]
I just ran into this too because of Prettier which formats:

```jsx
// works
import styles from './styles';

export default () =>
  <div>
    <h1 className="test">Hello</h1>
    <style jsx>{styles}</style>
  </div>;
```

into this:

```jsx
// doesn't work
import styles from './styles';

export default () =>
  <div>
    <h1 className="test">Hello</h1>
    <style jsx>
      {styles}
    </style>
  </div>;
```

Seems like the problem is already somewhat clear, here's the full stack trace anyway:

```
Module build failed: TypeError: /Users/akupila/Dev/style-jsx-bug/components/testpage.js: Invalid attempt to destructure non-iterable instance
    at /Users/akupila/Dev/style-jsx-bug/node_modules/babel-runtime/helpers/slicedToArray.js:48:13
    at PluginPass.exit (/Users/akupila/Dev/style-jsx-bug/node_modules/styled-jsx/dist/babel.js:250:66)
    at newFn (/Users/akupila/Dev/style-jsx-bug/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/Users/akupila/Dev/style-jsx-bug/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/akupila/Dev/style-jsx-bug/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/akupila/Dev/style-jsx-bug/node_modules/babel-traverse/lib/path/context.js:117:8)
    at TraversalContext.visitQueue (/Users/akupila/Dev/style-jsx-bug/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/Users/akupila/Dev/style-jsx-bug/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/Users/akupila/Dev/style-jsx-bug/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/Users/akupila/Dev/style-jsx-bug/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Users/akupila/Dev/style-jsx-bug/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/Users/akupila/Dev/style-jsx-bug/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/Users/akupila/Dev/style-jsx-bug/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/Users/akupila/Dev/style-jsx-bug/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/Users/akupila/Dev/style-jsx-bug/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Users/akupila/Dev/style-jsx-bug/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/Users/akupila/Dev/style-jsx-bug/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/Users/akupila/Dev/style-jsx-bug/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/Users/akupila/Dev/style-jsx-bug/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/Users/akupila/Dev/style-jsx-bug/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Users/akupila/Dev/style-jsx-bug/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/Users/akupila/Dev/style-jsx-bug/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/Users/akupila/Dev/style-jsx-bug/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/Users/akupila/Dev/style-jsx-bug/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/Users/akupila/Dev/style-jsx-bug/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Users/akupila/Dev/style-jsx-bug/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/Users/akupila/Dev/style-jsx-bug/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/Users/akupila/Dev/style-jsx-bug/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/Users/akupila/Dev/style-jsx-bug/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/Users/akupila/Dev/style-jsx-bug/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Users/akupila/Dev/style-jsx-bug/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/Users/akupila/Dev/style-jsx-bug/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/Users/akupila/Dev/style-jsx-bug/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/Users/akupila/Dev/style-jsx-bug/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/Users/akupila/Dev/style-jsx-bug/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Users/akupila/Dev/style-jsx-bug/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/Users/akupila/Dev/style-jsx-bug/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/Users/akupila/Dev/style-jsx-bug/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/Users/akupila/Dev/style-jsx-bug/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/Users/akupila/Dev/style-jsx-bug/node_modules/babel-traverse/lib/index.js:114:17)
    at traverse (/Users/akupila/Dev/style-jsx-bug/node_modules/babel-traverse/lib/index.js:79:12)
    at File.transform (/Users/akupila/Dev/style-jsx-bug/node_modules/babel-core/lib/transformation/file/index.js:548:35)
    at /Users/akupila/Dev/style-jsx-bug/node_modules/babel-core/lib/transformation/pipeline.js:50:19
    at File.wrap (/Users/akupila/Dev/style-jsx-bug/node_modules/babel-core/lib/transformation/file/index.js:564:16)
    at Pipeline.transform (/Users/akupila/Dev/style-jsx-bug/node_modules/babel-core/lib/transformation/pipeline.js:47:17)
    at transpile (/Users/akupila/Dev/style-jsx-bug/node_modules/babel-loader/lib/index.js:48:20)
    at /Users/akupila/Dev/style-jsx-bug/node_modules/babel-loader/lib/fs-cache.js:118:18
    at ReadFileContext.callback (/Users/akupila/Dev/style-jsx-bug/node_modules/babel-loader/lib/fs-cache.js:31:21)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:419:13)
```

I'll see if the fix proposed by @giuseppeg above works
