### ISSUE TITLE
Any way to use v2 with next.js right now?

### ISSUE THREAD

**Issue by mcansh** [zeit/styled-jsx#293]
Curious if theres anyway to use the beta over the bundled version with next.

```js
{
  "presets": ["next/babel"],
  "plugins": ["styled-jsx/babel"]
}
```
results in ```Module build failed: TypeError: unknown: Duplicate declaration "_JSXStyle"``` when starting next..

and not having a `.babelrc` at all results in 
```
Module build failed: SyntaxError: Expected a constant as part of the template literal expression (eg: <style jsx>{`p { color: ${myColor}`}</style>), but got a MemberExpression: this.color

  18 |         display: block;
  19 |         cursor: pointer;
> 20 |         background: ${props.color};
     |                       ^
  21 |       }
  22 |     `}</style>
  23 |   </button>
```

**Comment by giuseppeg** [comment]
@mcansh yeah see: https://github.com/zeit/styled-jsx/pull/204#issuecomment-333458495

**Comment by mcansh** [comment]
@giuseppeg thank you! Couldn't find it

**Comment by mcansh** [comment]
Hey @giuseppeg, i patched next's babel config but when using props in `<style jsx>` i get
```js
_style2.default.dynamic is not a function
TypeError: _style2.default.dynamic is not a function
    at Test (/Users/logansmcansh/Downloads/test/.next/dist/components/Test.js:26:32)
    at resolve (/Users/logansmcansh/Downloads/test/node_modules/react-dom/cjs/react-dom-server.node.development.js:2599:14)
    at ReactDOMServerRenderer.render (/Users/logansmcansh/Downloads/test/node_modules/react-dom/cjs/react-dom-server.node.development.js:2746:22)
    at ReactDOMServerRenderer.read (/Users/logansmcansh/Downloads/test/node_modules/react-dom/cjs/react-dom-server.node.development.js:2722:19)
    at renderToString (/Users/logansmcansh/Downloads/test/node_modules/react-dom/cjs/react-dom-server.node.development.js:2980:25)
    at renderPage (/Users/logansmcansh/Downloads/test/node_modules/next/dist/server/render.js:168:24)
    at Function.getInitialProps (/Users/logansmcansh/Downloads/test/node_modules/next/dist/server/document.js:83:25)
    at _callee$ (/Users/logansmcansh/Downloads/test/node_modules/next/dist/lib/utils.js:36:30)
    at tryCatch (/Users/logansmcansh/Downloads/test/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/Users/logansmcansh/Downloads/test/node_modules/regenerator-runtime/runtime.js:299:22)
```


babel-preset 
```js
const nextBabelPreset = require('next/babel');

nextBabelPreset.plugins = nextBabelPreset.plugins.map(plugin => {
  if (!Array.isArray(plugin) && plugin.indexOf('styled-jsx/babel') !== -1) {
    return require.resolve('styled-jsx/babel');
  }
  return plugin;
});

module.exports = nextBabelPreset;

```

**Comment by giuseppeg** [comment]
@mcansh try:

```
rm -rf node_modules/.cache .next
npm start dev
```

**Comment by mcansh** [comment]
i'm assuming you mean `npm run dev`?
if yeah, same result

**Comment by giuseppeg** [comment]
> i'm assuming you mean npm run dev?

yeah correct sorry. Ok I'll try to reproduce

**Comment by giuseppeg** [comment]
@mcansh it seems that thing changed a bit since the last time I checked
https://github.com/zeit/next.js/blob/master/server/build/webpack.js#L222-L245

@arunoda @nkzawa or @timneutkens might have suggestions on how to patch Next to use v2

**Comment by giuseppeg** [comment]
basically even if we patch Next's preset our plugin is ignored since the alias points to the old one - I think

**Comment by mcansh** [comment]
gothca, thanks for taking a look 👍

**Comment by timneutkens** [comment]
New version of `next@beta` is out with styled-jsx v2 🙌

**Comment by mcansh** [comment]
🎉🎉
