### ISSUE TITLE
Module styled-jsx/css not found

### ISSUE THREAD

**Issue by Mensae** [zeit/styled-jsx#302]
Following [this](https://github.com/zeit/styled-jsx#keeping-css-in-separate-files) step (css must be imported from styled-jsx/css) I am getting the error "This module was not found".

And this is correct, but incorrect, as this is indeed not there.

next: 3.2.2
styled-jsx: 2.0.1

**Comment by giuseppeg** [comment]
`next@3.2.2` is not shipping with `styled-jsx@2.0.1` that's why, you need to switch to `next@4`

**Comment by Mensae** [comment]
Hi @giuseppeg 

Thanks for you reply.

Unfortunately it seems not that easy. I actually manually installed styled-jsx v2.0.1 but I've update next to version 4.0.1 now, and just to be sure I removed the node_modules folder first and installed all packages over again.

Still, same result: Webstorm sais "module not installed" and from the terminal:

`ReferenceError: css is not defined
    at Object.<anonymous> (C:\Users\Johan\Projects\WebstormProjects\myProject-react\components\SiteHeader\index.js:16:7)
    at Module._compile (module.js:624:30)
    at Module._compile (C:\Users\Johan\Projects\WebstormProjects\myProject-react\node_modules\source-map-support\source-map-suppo
rt.js:492:25)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Johan\Projects\WebstormProjects\myProject-react\components\Layout\index.js:4:1)
ReferenceError: css is not defined
    at Object.<anonymous> (C:\Users\Johan\Projects\WebstormProjects\myProject-react\components\SiteHeader\index.js:16:7)
    at Module._compile (module.js:624:30)
    at Module._compile (C:\Users\Johan\Projects\WebstormProjects\myProject-react\node_modules\source-map-support\source-map-suppo
rt.js:492:25)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Johan\Projects\WebstormProjects\myProject-react\components\Layout\index.js:4:1)
`

`import React, {Component} from 'react';
import css from 'styled-jsx/css';
...
const styledHeader = css``
  header {
    minHeight: '4.3rem',
  }
``;
`
