### ISSUE TITLE
Error on creating style tags recursively

### ISSUE THREAD

**Issue by a-ignatov-parc** [zeit/styled-jsx#364]
I'm having an issue rendering multiple font faces recursively creating `style` tags.

```jsx
return (
  <div>
    {fontFaces.map(fontFace => (
      <style jsx global>{`
        @font-face {
          font-family: ${fontFace.fontFamily};
          font-weight: ${fontFace.fontWeight};
          src: ${fontFace.src};
        }
      `}</style>
    ))}
    <style jsx global>{`
      html, body {
        background: ${theme.colors.layout};
      }
    `}</style>
  </div>
);
```

Build constantly failing with
```
Error: Module build failed: TypeError: /index.js: Cannot read property 'start' of undefined
    at processCss (/node_modules/styled-jsx/dist/_utils.js:452:50)
    at PluginPass.exit (/node_modules/styled-jsx/dist/babel.js:219:51)
    at newFn (/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/node_modules/babel-traverse/lib/path/context.js:117:8)
    at TraversalContext.visitQueue (/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/node_modules/babel-traverse/lib/path/context.js:115:19)
```

Any ideas how I can handle this case not using `JSXStyle` component directly?

```jsx
return (
  <div>
    <JSXStyle
      styleId='font-faces'
      css={fontFaces.map(fontFace => `
        @font-face {
          font-family: ${fontFace.fontFamily};
          font-weight: ${fontFace.fontWeight};
          src: ${fontFace.src};
        }
      `)}
    />
    <style jsx global>{`
      html, body {
        background: ${theme.colors.layout};
      }
    `}</style>
  </div>
);
```

**Comment by giuseppeg** [comment]
Yeah whenever the `style` tag is not direct descendant (child) of the outer div (the root of the component) styles are ignored and then it throws with a confusing error. 

Relates to #365.
Need to merge #260.

**Comment by a-ignatov-parc** [comment]
Great! Thanks 👍

**Comment by a-ignatov-parc** [comment]
@giuseppeg any news on new version release with https://github.com/zeit/styled-jsx/pull/260?

**Comment by giuseppeg** [comment]
@a-ignatov-parc somebody should fix https://github.com/zeit/styled-jsx/pull/372 but I don't have time

**Comment by a-ignatov-parc** [comment]
Ok. If I'll find time will dig into it 👍
