### ISSUE TITLE
Why does this code throw "Cannot read property 'start' of undefined"?

### ISSUE THREAD

**Issue by valnub** [zeit/styled-jsx#365]
```jsx
import React, { Component } from 'react';

class testpage extends Component {
  render() {
    return (
      <div>
        <p>test</p>
        <style jsx>{`
          p {
            color: green;
          }
        `}
        </style>

        <div>
          <div className="foo">test</div>
          <style jsx>{`
            .foo {
              color: red;
            }
          `}
          </style>
        </div>
      </div>
    );
  }
}

export default testpage;

```

Gives:

```
Error in pages/testpage.js?entry
Module build failed: TypeError: pages/testpage.js?entry: Cannot read property 'start' of undefined
    at processCss (node_modules/styled-jsx/dist/_utils.js:452:49)
    at PluginPass.exit (node_modules/styled-jsx/dist/babel.js:219:51)
    at newFn (node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (node_modules/babel-traverse/lib/path/context.js:117:8)
    at TraversalContext.visitQueue (node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (node_modules/babel-traverse/lib/index.js:114:17)
```

However, the following works. Why is that so?

```jsx
import React, { Component } from 'react';

class testpage extends Component {
  render() {
    return (
      <div>
        <p>test</p>
        <style jsx>{`
          p {
            color: green;
          }
        `}
        </style>

        <div className="foo">test</div>
        <style jsx>{`
          .foo {
            color: red;
          }
        `}
        </style>
      </div>
    );
  }
}

export default testpage;
```

**Comment by giuseppeg** [comment]
because of the nested style tags I suppose. Only direct descendants of the outer div work. Need to merge #260
