### ISSUE TITLE
conditional style block

### ISSUE THREAD

**Issue by javialon26** [zeit/styled-jsx#386]
Hello i'm trying to render a conditional style jsx but i don't know if it is possible.

This is the code but i get an error:

```import React from 'react';

const Col = ({ children, lg }) => {
  const lgw = (lg / 12) * 100;

  return (
    <div className="col">
      <style jsx>{`
      .col {
        flex-basis: 100%;
        max-width: 100%;
      }
      `}
      </style>
      {lgw &&
        <style jsx>{`
          @media(min-width: 1200px) {
            .col {
              flex-basis: ${lgw}%;
              max-width: ${lgw}%;
            }
          }
        `}
        </style>
      }
      {children}
    </div>
  );
};

export default Col;
```

Error:
```ERROR in ./src/Col/Col.js
Module build failed: TypeError: /usr/src/app/src/Col/Col.js: Cannot read property 'start' of undefined
    at processCss (/usr/src/app/node_modules/styled-jsx/dist/_utils.js:452:50)
    at PluginPass.exit (/usr/src/app/node_modules/styled-jsx/dist/babel.js:219:51)
    at newFn (/usr/src/app/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/usr/src/app/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/usr/src/app/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/usr/src/app/node_modules/babel-traverse/lib/path/context.js:117:8)
    at TraversalContext.visitQueue (/usr/src/app/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/usr/src/app/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/usr/src/app/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/usr/src/app/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/usr/src/app/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/usr/src/app/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/usr/src/app/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/usr/src/app/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/usr/src/app/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/usr/src/app/node_modules/babel-traverse/lib/path/context.js:115:19)
 @ ./src/index.js 15:11-31
 @ ./stories/index.js
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/react/dist/server/config/polyfills.js ./node_modules/@storybook/react/dist/server/config/globals.js (webpack)-hot-middleware/client.js?reload=true ./.storybook/config.js
```

Thank you!

**Comment by a-ignatov-parc** [comment]
It's not possible yet (see https://github.com/zeit/styled-jsx/issues/364 and https://github.com/zeit/styled-jsx/pull/372 for more info) but there is a workaround.

You can use [`resolveScopedStyles`](https://github.com/zeit/styled-jsx#styling-third-parties--child-components-from-the-parent).

```jsx
const Col = ({ children, lg }) => {
  const lgw = (lg / 12) * 100;

  const scoped = resolveScopedStyles((
    <scope>
      <style jsx>{`
        @media(min-width: 1200px) {
          .col {
            flex-basis: ${lgw}%;
            max-width: ${lgw}%;
          }
        }
      `}</style>
    </scope>
  ));

  return (
    <div className={`col ${scoped.className}`}>
      <style jsx>{`
        .col {
          flex-basis: 100%;
          max-width: 100%;
        }
      `}
      </style>
      {lgw && scoped.styles}
      {children}
    </div>
  );
};
```

**Comment by giuseppeg** [comment]
what @a-ignatov-parc suggested or you can also make two separate components:

```jsx
const ResponsiveCol = ({children, size}) => (
   <div className="col">
       <style jsx>{`
        @media(min-width: 1200px) {
          .col {
            flex-basis: ${size}%;
            max-width: ${size}%;
          }
        }
      `}</style>
       {children}
   </div>
)

// and

const Col = ({ children, lg }) => {
  const lgw = (lg / 12) * 100;
  return lgw ? <ResponsiveCol size={lgw}>{children}</ResponsiveCol> : 
    <div className="col">
      <style jsx>{`
        .col {
          flex-basis: 100%;
          max-width: 100%;
        }
      `}
      </style>
      {children}
    </div>
}
```

**Comment by GandharvJaggiCD** [comment]
Hi, what are the current ways to achieve it?? I am trying to conditionally add a `style jsx` tag

`{wantStyles && <style jsx>{Styles}</style>}` but it gives out an error
`If you want to write it to the DOM, pass a string instead: jsx="true" or jsx={value.toString()}.`

is there a way out?
