### ISSUE TITLE
Upgrade build toolchain to use babel@7 to match next@6

### ISSUE THREAD

**Issue by vjpr** [zeit/styled-jsx#445]
Two things:

- `styled-jsx` depends on `babel-runtime@6`. The latest `next@6` uses `babel@7.0.0-beta.42`. It would be great if `styled-jsx` was built against `@babel/runtime@7`. Would avoid needing both `babel-runtime@6` and v7 which increase bundle size. 

- `styled-jsx` is missing `babel-runtime@^6` in its dependencies. See comment below.

```
 Error: [BABEL] /xxx/foo.js: Cannot find module 'babel-runtime/helpers/slicedToArray' (While processing: "base$0$0$0")
      at Function.Module._resolveFilename (module.js:536:15)
      at Function.Module._load (module.js:466:25)
      at Module.require (module.js:579:17)
      at require (internal/module.js:11:18)
      at Object.<anonymous> (/xxx/node_modules/.registry.npmjs.org/styled-jsx/2.2.1/node_modules/styled-jsx/dist/babel.js:7:23)
      at Module._compile (module.js:635:30)
      at Object.Module._extensions..js (module.js:646:10)
      at Module.load (module.js:554:32)
      at tryModuleLoad (module.js:497:12)
      at Function.Module._load (module.js:489:3)
      at Module.require (module.js:579:17)
      at require (internal/module.js:11:18)
```

**Comment by vjpr** [comment]
_style.js_

```
var _map = require('babel-runtime/core-js/map');

var _map2 = _interopRequireDefault(_map);

var _slicedToArray2 = require('babel-runtime/helpers/slicedToArray');

var _slicedToArray3 = _interopRequireDefault(_slicedToArray2);

var _getPrototypeOf = require('babel-runtime/core-js/object/get-prototype-of');

var _getPrototypeOf2 = _interopRequireDefault(_getPrototypeOf);

var _classCallCheck2 = require('babel-runtime/helpers/classCallCheck');

var _classCallCheck3 = _interopRequireDefault(_classCallCheck2);

var _createClass2 = require('babel-runtime/helpers/createClass');

var _createClass3 = _interopRequireDefault(_createClass2);

var _possibleConstructorReturn2 = require('babel-runtime/helpers/possibleConstructorReturn');

var _possibleConstructorReturn3 = _interopRequireDefault(_possibleConstructorReturn2);

var _inherits2 = require('babel-runtime/helpers/inherits');

var _inherits3 = _interopRequireDefault(_inherits2);
```

**Comment by giuseppeg** [comment]
Hi thanks for opening an issue. Can you add a more meaningful description for the issue?

**Comment by vjpr** [comment]
@giuseppeg Done.

**Comment by giuseppeg** [comment]
Can you make a PR to add `babel-runtime@^6`? In styled-jsx v3 which we will release soon we probably won't need babel-runtime at all
