### ISSUE TITLE
Conditionally Adding Styled JSX

### ISSUE THREAD

**Issue by atif089** [zeit/styled-jsx#453]
* OS: Windows 10
* Browser: Chrome 65
* styled-jsx (version): 2.2.5

I'm not sure if this is a bug or if I'm doing something incorrectly. What is the right way to add `<style jsx` tags conditionally?

For example in my current situation

```
<style jsx>{MastHeadStyles}</style>
<style jsx>{MastHeadClearanceStyles}</style>
```

the above works fine, but the following throws an error

```
<style jsx>{MastHeadStyles}</style>
{this.props.isClearancePage && (
  <style jsx>{MastHeadClearanceStyles}</style>
)}
```

Logs

```
ModuleBuildError: Module build failed: TypeError:
Cannot read property 'length' of undefined
    at hash (_path_to_the_project__\node_modules\string-hash\index.js:5:18)
    at hashString (_path_to_the_project__\node_modules\next\node_modules\styled-jsx\dist\_utils.js:57:42)
    at processCss (_path_to_the_project__\node_modules\next\node_modules\styled-jsx\dist\_utils.js:461:64)
    at PluginPass.exit (_path_to_the_project__\node_modules\next\node_modules\styled-jsx\dist\babel.js:226:51)
    at newFn (_path_to_the_project__\node_modules\babel-traverse\lib\visitors.js:276:21)
    at NodePath._call (_path_to_the_project__\node_modules\babel-traverse\lib\path\context.js:76:18)
    at NodePath.call (_path_to_the_project__\node_modules\babel-traverse\lib\path\context.js:48:17)
    at NodePath.visit (_path_to_the_project__\node_modules\babel-traverse\lib\path\context.js:117:8)
    at TraversalContext.visitQueue (_path_to_the_project__\node_modules\babel-traverse\lib\context.js:150:16)
    at TraversalContext.visitSingle (_path_to_the_project__\node_modules\babel-traverse\lib\context.js:108:19)
    at TraversalContext.visit (_path_to_the_project__\node_modules\babel-traverse\lib\context.js:192:19)
    at Function.traverse.node (_path_to_the_project__\node_modules\babel-traverse\lib\index.js:114:17)
    at NodePath.visit (_path_to_the_project__\node_modules\babel-traverse\lib\path\context.js:115:19)
    at TraversalContext.visitQueue (_path_to_the_project__\node_modules\babel-traverse\lib\context.js:150:16)
    at TraversalContext.visitSingle (_path_to_the_project__\node_modules\babel-traverse\lib\context.js:108:19)
    at TraversalContext.visit (_path_to_the_project__\node_modules\babel-traverse\lib\context.js:192:19)
```

**Comment by vivaldus** [comment]
Can't you pull all your logic into a single style tag? `<style jsx>{`${/* LOGIC HERE */}`}</style>`

**Comment by atif089** [comment]
@vivaldus  How can I compute the logic and print it? I think I can use a ternary operator for now, but what if I have 3 such conditions and wouldn't want to use nested ternary operators

**Comment by MagnusBrzenk** [comment]
I'm not used to including objects within my <style jsx> brackets. I just use string-formatting logic. So if I wanted to include, say, the following content:

```js
const demoClassString = `
   .demo-class{
      background-color: red;
   }
`
```

...  conditioned on some boolean `bAddDemoClass` then I'd just use:

```js
   <style jsx>
      {
         `${bAddDemoClass ? demoClassString : ""}`
      }
   </style>
```
If the logic were more complicated than this, then you can pull it out into the render function (before returning your `jsx`). BTW, I think it's better practice to not conditionally include whole css blocks, rather, it's better to have somewhat constant css blocks (though I parameterise their properties all the time with `${}`), and, rather, to conditionally alter/add/subtract class names to your `jsx` elements with `this.state.bSomeBoolean`.

**Comment by vivaldus** [comment]
I'm not used to including objects within my <style jsx> brackets. I just use string-formatting logic. So if I wanted to include, say, the following content:

```js
const demoClassString = `
   .demo-class{
      background-color: red;
   }
`
```

...  conditioned on some boolean `bAddDemoClass` then I'd just use:

```js
   <style jsx>
      {
         `${bAddDemoClass ? demoClassString : ""}`
      }
   </style>
```
If the logic were more complicated than this, then you can pull it out into the render function (before returning your `jsx`). BTW, I think it's better practice to not conditionally include whole css blocks, rather, it's better to have somewhat constant css blocks (though I parameterise their properties all the time with `${}`), and, rather, to conditionally alter/add/subtract class names to your `jsx` elements with `this.state.bSomeBoolean`.

**Comment by michaelwschultz** [comment]
@atif089 not sure placing a condition on the <style jsx> element is really what you want to do. I'd take a look at this module https://github.com/JedWatson/classnames.

This way you can place all your conditions in your markup which should be more readable although potentially a little more code.

#### Example
```
<div
  className={classNames( { 'masthead', 'mastheadClearance': mastHeadClearanceStyles})}
>

<style jsx>{`
  .masthead {
    background: red;
  }
 .mastheadClearance {
    background: blue;
  }
`}</style>
```

This will add `.masthead` by default, then if mastHeadClearanceStyles is true, `.mastheadClearance` will be added.

**Comment by giuseppeg** [comment]
with styled-jsx v3 you can use this https://github.com/zeit/styled-jsx#the-resolve-tag for special cases like this one

**Comment by Ashfaqe-oss** [comment]
How can I add the className conditionally in next ?
