### ISSUE TITLE
Build with source maps fails using awesome-typescript-loader

### ISSUE THREAD

**Issue by Peping** [zeit/styled-jsx#479]
#### Do you want to request a *feature* or report a *bug*?
This is a **bug**

#### What is the current behavior?
Babel compile step throws an exception trying to create source maps. It appears the `styled-jsx/babel` plugin isn't given exactly the data it expects.

    ERROR in ./src/index.tsx
    Module build failed (from ./node_modules/awesome-typescript-loader/dist/entry.js):
    TypeError: Cannot read property 'indexOf' of undefined
        at Object.relative (C:\Users\peping\WebstormProjects\styled-jsx-demo\node_modules\styled-jsx\node_modules\source-map\lib\util.js:262:16)
        at SourceMapGenerator.setSourceContent (C:\Users\peping\WebstormProjects\styled-jsx-demo\node_modules\styled-jsx\node_modules\source-map\lib\source-map-generator.js:140:21)
        at makeSourceMapGenerator (C:\Users\peping\WebstormProjects\styled-jsx-demo\node_modules\styled-jsx\dist\_utils.js:383:13)
        at processCss (C:\Users\peping\WebstormProjects\styled-jsx-demo\node_modules\styled-jsx\dist\_utils.js:484:21)
        at PluginPass.exit (C:\Users\peping\WebstormProjects\styled-jsx-demo\node_modules\styled-jsx\dist\babel.js:220:51)
        at newFn (C:\Users\peping\WebstormProjects\styled-jsx-demo\node_modules\@babel\traverse\lib\visitors.js:193:21)
        at NodePath._call (C:\Users\peping\WebstormProjects\styled-jsx-demo\node_modules\@babel\traverse\lib\path\context.js:53:20)
        at NodePath.call (C:\Users\peping\WebstormProjects\styled-jsx-demo\node_modules\@babel\traverse\lib\path\context.js:40:17)
        at NodePath.visit (C:\Users\peping\WebstormProjects\styled-jsx-demo\node_modules\@babel\traverse\lib\path\context.js:97:8)
        at TraversalContext.visitQueue (C:\Users\peping\WebstormProjects\styled-jsx-demo\node_modules\@babel\traverse\lib\context.js:118:16)
     @ multi ./src main[0]

#### If the current behavior is a bug, please provide the steps to reproduce and possibly a minimal demo or testcase in the form of a Next.js app, CodeSandbox URL or similar

The bug is demonstrated [**in my repo**](https://github.com/Peping/styled-jsx-demo).

#### What is the expected behavior?
Build should succeed and source maps should be generated. 

As a workaround, I'm opting for building without source maps by setting `"sourceMaps": false`. 

By the way, [the README of styled-jsx](https://github.com/zeit/styled-jsx#sourcemaps) says the default should be `false`, while it quite obviously is not in my case. How so?

#### Environment (include versions)

* OS: Windows 10 build 17134
* Browser: _not applicable_ - fails during compile
* styled-jsx (version): 2.2.4
* [package-lock.json](https://github.com/Peping/styled-jsx-demo/blob/master/package-lock.json)

#### Did this work in previous versions?
I haven't tested previous versions as of yet.

**Comment by giuseppeg** [comment]
does this happen with both version ^2.2.4 and ^3.0.2 of styled-jsx? Also is Babel 7 a requirement or can you also use Babel 6? We officially don't support Babel 7 yet, we are waiting for a stable release.
