### ISSUE TITLE
Version incompatibility using Next 7.0.2 & styled-jsx 3.2.0

### ISSUE THREAD

**Issue by Maxwell2022** [zeit/styled-jsx#543]
We noticed an error in one of our staging server today. It looks like there is version incompatibility between `next 7.0.2` and `styled-jsx 3.2.0`. It's building fine however running the server we get the following error:

```
2019-01-21T07:33:12.709Z    70e9ebe4-8def-4d38-9346-568d93635fca    Error while running `getDataFromTree` TypeError: Cannot read property 'replace' of undefined
at sanitize (/var/task/node_modules/styled-jsx/dist/stylesheet-registry.js:21:15)
at StyleSheetRegistry.computeSelector (/var/task/node_modules/styled-jsx/dist/stylesheet-registry.js:207:17)
at StyleSheetRegistry.getIdAndRules (/var/task/node_modules/styled-jsx/dist/stylesheet-registry.js:234:22)
at StyleSheetRegistry.add (/var/task/node_modules/styled-jsx/dist/stylesheet-registry.js:80:38)
at JSXStyle.render (/var/task/node_modules/styled-jsx/dist/style.js:74:28)
at c (/var/task/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:30:231)
at Ga (/var/task/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:31:1)
at a.render (/var/task/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:367)
at a.read (/var/task/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:35:450)
at renderToStaticMarkup (/var/task/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:47:179)
```

Replace this version of `styled-jsx` with the `version 3.1.0` is fixing our error.

Not really sure what is going on

**Comment by ssylvia** [comment]
Had this same issue. It works at v3.1.2 but bot v3.1.3

**Comment by ijjk** [comment]
@Maxwell2022 @ssylvia does [this reply](https://github.com/zeit/styled-jsx/issues/545#issuecomment-457096043) help or are you handling updating the `styled-jsx` version differently? If it's different, can you upload a small reproduction?

**Comment by giuseppeg** [comment]
what @ijjk said :)

**Comment by mhauens** [comment]
same problem with next 9.1.1 and  "styled-jsx": "3.1.3" or higher
