### ISSUE TITLE
Bug in babel plugin since version 0.4.4

### ISSUE THREAD

**Issue by romainneutron** [zeit/styled-jsx#82]
Here's the stack trace:

```
ERROR in ./app/Resources/assets/js/react/jsx/Form/VariablesForm.js
Module build failed: TypeError: .../app/Resources/assets/js/react/jsx/Form/VariablesForm.js: Cannot read property 'name' of undefined
    at .../node_modules/styled-jsx/dist/babel.js:18:23
    at Array.some (native)
    at isGlobalEl (.../node_modules/styled-jsx/dist/babel.js:17:26)
    at PluginPass.exit (.../node_modules/styled-jsx/dist/babel.js:185:26)
    at newFn (.../node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (.../node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (.../node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (.../node_modules/babel-traverse/lib/path/context.js:117:8)
    at TraversalContext.visitQueue (.../node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (.../node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (.../node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (.../node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (.../node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (.../node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitQueue (.../node_modules/babel-traverse/lib/context.js:156:21)
    at TraversalContext.visitSingle (.../node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (.../node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (.../node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (.../node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (.../node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (.../node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (.../node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (.../node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (.../node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (.../node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (.../node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (.../node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (.../node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (.../node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (.../node_modules/babel-traverse/lib/context.js:150:16)
 @ ./app/Resources/assets/js/react/components/BuildSettings/VariablesEdit/Modal.js 18:0-60
 @ ./app/Resources/assets/js/react/components/BuildSettings/VariablesEdit/VariablesEditButton.js
 @ ./app/Resources/assets/js/react/components/BuildSettings/VariablesEdit/index.js
 @ ./app/Resources/assets/js/react/jsx/Dashboard/SubComp/BuildSettings.js
 @ ./app/Resources/assets/js/react/jsx/Dashboard/SubComp/BuildList.js
 @ ./app/Resources/assets/js/react/jsx/Dashboard/SubComp/AsyncBuildList.js
 @ ./app/Resources/assets/js/react/containers/dashboard-routing.js
 @ ./app/Resources/assets/js/react/containers/dashboard.prod.js
 @ ./app/Resources/assets/js/react/containers/dashboard.js
 @ ./app/Resources/assets/js/react/dashboard-bundle.js
 @ multi ./app/Resources/assets/js/react/webpack-bootstrap ./app/Resources/assets/js/react/dashboard-bundle
```

**Comment by giuseppeg** [comment]
@romainneutron can you share the source code?

**Comment by romainneutron** [comment]
I'm gonna try to reduce and get a small reproducer

**Comment by giuseppeg** [comment]
@romainneutron any luck?

**Comment by benhjames** [comment]
Here is the minimal version I could get to reproduce the same error (the stack trace is the same as the one above).

pages/index.js:

```js
import page from '../hocs/page';

export default page(() => (
  <div>
    <p>Hey</p>
    <style jsx>{`
      p {
        color: red;
      }
    `}</style>
  </div>
));
```

hocs/page.js:

```js
import React, { Component } from 'react';

export default WrappedComponent => {
  class Page extends Component {
    render() {
      return <WrappedComponent {...this.props} />;
    }
  }

  return Page;
};
```

Interestingly, as soon as I remove `{...this.props}`, it compiles fine!

I'm using `next.js` straight from `master` if that makes a difference. Hope this helps. 😄

**Comment by benhjames** [comment]
For the sake of completeness, I can also confirm this was introduced in 0.4.4, works fine in 0.4.3.

**Comment by giuseppeg** [comment]
@benhjames thanks! That makes sense, the spread operator is the problem since `JSXSpreadAttribute` doesn't have a `name` property. I'll fix that later :)

**Comment by romainneutron** [comment]
Thanks @benhjames , I was going to look for the reproducer this afterrnoon, you saved me some time 🍻
